import re

class OracleToMySQLConverter:
    def __init__(self):
        pass

    def preprocess(self, sql: str) -> str:
        """Remove Oracle-specific noise"""
        # Remove REM/PROMPT/SET lines
        sql = re.sub(r'^\s*rem.*$', '', sql, flags=re.MULTILINE | re.IGNORECASE)
        sql = re.sub(r'^\s*prompt.*$', '', sql, flags=re.MULTILINE | re.IGNORECASE)
        sql = re.sub(r'^\s*set.*$', '', sql, flags=re.MULTILINE | re.IGNORECASE)

        # Remove SQL*Plus variables like &tbs, &pass
        sql = re.sub(r'&\w+', '', sql)
        return sql

    def split_statements(self, sql: str):

        # statements = []
        # current = []
# 
        # for line in sql.splitlines():
        #     current.append(line)
        #     if ';' in line:
        #         statements.append('\n'.join(current))
        #         current = []
# 
        # return [s.strip() for s in statements if s.strip()]
        statements = []
        current = []
        in_string = False
        in_parentheses = False

        for char in sql:
            if char == "'":
                in_string = not in_string
            # if char == "(":
            #     in_string = not in_parentheses
    # 
            if char == ';' and not in_string:
                statements.append(''.join(current).strip())
                current = []
            else:
                current.append(char)
    
        # Catch anything left
        if current:
            statements.append(''.join(current).strip())
    
        return [s for s in statements if s]
        
    def get_statement_type(self, stmt: str):
        stmt_clean = stmt.strip().upper()
    
        if stmt_clean.startswith("CREATE TABLE"):
            return "CREATE_TABLE"
        elif stmt_clean.startswith("CREATE INDEX"):
            return "CREATE_INDEX"
        elif stmt_clean.startswith("ALTER TABLE"):
            return "ALTER_TABLE"
        elif stmt_clean.startswith("CREATE OR REPLACE VIEW"):
            return "VIEW"
        else:
            return "OTHER"

    def convert(self, sql: str) -> str:
        sql = self.preprocess(sql)
        statements = self.split_statements(sql)
    
        converted = []
        skipped = []
        
        for stmt in statements:
            stmt_type = self.get_statement_type(stmt)
            #print(stmt)
            if stmt_type == "CREATE_TABLE":
                converted.append(self.convert_create_table(stmt))
            elif stmt_type == "CREATE_INDEX":
                converted.append(self.convert_index(stmt))
            elif stmt_type == "ALTER_TABLE":
                converted.append(self.convert_alter(stmt))
            else:
                skipped.append(stmt_type)
                print("Skipped: ", stmt)
        print("Skipped:", set(skipped))

        return "\n\n".join(converted)
        
        
    def convert_create_table(self, stmt: str) -> str:
        # Old method -- not removed yet just in case
        # stmt = re.sub(r'VARCHAR2\((\d+)\s+CHAR\)', r'VARCHAR(\1)', stmt, flags=re.IGNORECASE)
        # stmt = re.sub(r'NUMBER\((\d+),(\d+)\)', r'DECIMAL(\1,\2)', stmt, flags=re.IGNORECASE)
        # stmt = re.sub(r'\bINTEGER\b', 'INT', stmt, flags=re.IGNORECASE)
# 
        # stmt = re.sub(
        #     r'INT\s+GENERATED BY DEFAULT ON NULL AS IDENTITY',
        #     'INT AUTO_INCREMENT',
        #     stmt,
        #     flags=re.IGNORECASE
        # )
# 
        # auto_inc_column = None
        # match = re.search(r'(\w+)\s+INT AUTO_INCREMENT', stmt, re.IGNORECASE)
        # if match:
        #     auto_inc_column = match.group(1)
# 
        # if auto_inc_column and "PRIMARY KEY" not in stmt.upper():
        #     stmt = stmt.rstrip(');\n') + f",\n  PRIMARY KEY ({auto_inc_column})\n);"
# 
        # return stmt
        table_name = re.search(r'CREATE TABLE (\w+)', stmt, re.IGNORECASE).group(1)
    
        columns = self.parse_columns(stmt)
    
        new_columns = []
        primary_key = None
    
        for col in columns:
            line = col["raw"]
    
            # Type conversions
            line = re.sub(r'VARCHAR2\((\d+)\s+CHAR\)', r'VARCHAR(\1)', line, flags=re.IGNORECASE)
            line = re.sub(r'NUMBER\((\d+),(\d+)\)', r'DECIMAL(\1,\2)', line, flags=re.IGNORECASE)
            line = re.sub(r'\bINTEGER\b', 'INT', line, flags=re.IGNORECASE)
    
            # Identity handling
            if "GENERATED BY DEFAULT ON NULL AS IDENTITY" in line.upper():
                line = re.sub(
                    r'INT\s+GENERATED BY DEFAULT ON NULL AS IDENTITY',
                    'INT AUTO_INCREMENT',
                    line,
                    flags=re.IGNORECASE
                )
                primary_key = col["name"]
    
            new_columns.append(line)
    
        # Add primary key if needed
        if primary_key:
            new_columns.append(f"PRIMARY KEY ({primary_key})")
    
        return f"CREATE TABLE {table_name} (\n  " + ",\n  ".join(new_columns) + "\n);"
            
        
    def convert_index(self, stmt: str) -> str:
        return stmt
        
        
    def convert_alter(self, stmt: str) -> str:
        # Convert VARCHAR2 
        stmt = re.sub(r'VARCHAR2', 'VARCHAR', stmt, flags=re.IGNORECASE)

        # Convert NUMBER
        stmt = re.sub(r'NUMBER\((\d+),(\d+)\)', r'DECIMAL(\1,\2)', stmt, flags=re.IGNORECASE)

        return stmt   
            
    def parse_columns(self, stmt: str):
        """Extract column definitions"""
        inside = re.search(r'\((.*)\)', stmt, re.DOTALL)
        if not inside:
            return []
    
        columns_block = inside.group(1)
    
        columns = []
        raw_columns = self.split_columns(columns_block)
        
        columns = []
        for col in raw_columns:
            parts = col.split()
            if not parts:
                continue
        
            columns.append({
                "name": parts[0],
                "raw": col
            })
        
        return columns
        
        
    def split_columns(self, columns_block: str):
        columns = []
        current = []
        depth = 0
        in_string = False
    
        for char in columns_block:
            if char == "'":
                in_string = not in_string
    
            elif not in_string:
                if char == '(':
                    depth += 1
                elif char == ')':
                    depth -= 1
    
            # Only split on commas at top level
            if char == ',' and depth == 0 and not in_string:
                columns.append(''.join(current).strip())
                current = []
            else:
                current.append(char)
    
        if current:
            columns.append(''.join(current).strip())
    
        return columns